Automatic addition of this and final qualifier no longer works in 0.18 #96
Error: plugin-java.xml is not included in the generated jar and thus the java related component and actions are not activated

Solution: Moved META-INF to src, so that plugin-java.xml is also included in the generated jar
Based on https://intellij-support.jetbrains.com/hc/en-us/community/posts/206108699-Build-against-Rubymine-SDK-not-working-when-using-depends-optional-true